#!/bin/bash

SERVICE_NAME="Generic System"
PATH_TO_EXEC="/home/middleware/git/gs-demo/"
PID_PATH_NAME="$HOME/.tmp/GenericSystem-pid"

# Function to start the app
do_start(){
    echo "Starting $SERVICE_NAME ..."
    if [ ! -f $PID_PATH_NAME ]; then
        cd $PATH_TO_EXEC;
        mvn clean validate install exec:java -Dexec.mainClass="org.genericsystem.demo.App" -Dexec.args="8080" 2>>/home/middleware/log/error.log >>/home/middleware/log/genericsystem.log &
        echo $! > $PID_PATH_NAME
	echo "$SERVICE_NAME is started with pid $(cat $PID_PATH_NAME)"
    else
       	echo "$SERVICE_NAME is already running ..."
        # Try a restart?
    fi
}

# Function to stop the app
do_stop() {
    if [ -f $PID_PATH_NAME ]; then
	PID=$(cat $PID_PATH_NAME);
	echo "$SERVICE_NAME is stopping ..."
	echo "killing processus : $PID"
	kill $PID
        wait $PID
	echo "$SERVICE_NAME is stopped"
	PID_PATH_NAME=""
    else
	echo "$SERVICE_NAME is not running"
    fi
}

# Main
case $1 in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart)
        do_stop && do_start
	;;
    *)
        echo "Usage: genericsystem {start|stop|restart}" >&2
        ;;
esac
